function [perFrameHeader] = getPerFrameHeaderPropsFromVersion(verInfo)
% NOTE: This method exists for back-wards compatibility only. The opentif method and the TIFF header spec are being 
%       revised to remove the need for complicated parsing, making this file unnecessary.

% Returns a cell array of strings for each property that
% can change from frame to frame in the TIFF header
% The first output shows the values that should be turned into an array,
% while the second output shows the ones that should be turned into a cell array

    if verInfo.infoFound
        perFrameHeader.forArray = {   ...
            'frameNumbers'...
            'acquisitionNumbers'...
            'frameNumberAcquisition'...
            'frameTimestamps'...
            'acqTriggerTimestamps'...
            'nextFileMarkerTimestamps'...
            'endOfAcquisition'...
            'endOfAcquisitionMode'...
            'dcOverVoltage'...
            };
        
        perFrameHeader.forCellArray = {'epoch'};
        
        if strcmp(verInfo.ImagingSystemType, 'Resonant')
            perFrameHeader.forCellArray = union(perFrameHeader.forCellArray,...
                {...
                'auxTrigger0'...
                'auxTrigger1'...
                'auxTrigger2'...
                'auxTrigger3'...
                'I2CData'...
                });
        end
        
    else
        perFrameHeader.forArray = {};
        perFrameHeader.forCellArray = {};
    end
end


%--------------------------------------------------------------------------%
% getPerFrameHeaderPropsFromVersion.m                                      %
% Copyright © 2016 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage 2015 is premium software to be used under the purchased terms  %
% Code may be modified, but not redistributed without the permission       %
% of Vidrio Technologies, LLC                                              %
%--------------------------------------------------------------------------%
